<?php
$conf=array(
//基础参数
'isinstall'=>'0',//网站安装状态（0为未安装，1为已安装）
'webmode'=>'1',//网站状态（0为关闭，1为运行）
'welcome'=>'您现在使用的是zzzcms开源建站系统，欢迎您对本系统提出宝贵的建议，请务必保留版权说明，严禁私自修改、出售等行为，本站保留法律追究的权利。',//网站状态（0为关闭，1为运行）
'showtime'=>'0',//显示执行时间
'iscode'=>'1',//开启验证码（1开启）
'isdel'=>'0',//内容和分类是否直接删除不进入回收站（1开启）
'tianqimark'=>'1',//后台是否显示天气（0关闭,1开启可关闭,2开启）
'bugmark'=>'0',//调试模式
'sitepath'=>'/',//网站总目录例如:/cms/
'adminpath'=>'admin/',//网站后台总目录例如:admin_aspcms
'closeinfo'=>'很抱歉，升级维护中！,开通时间另行通知！电话：+86-010-88888888',//网站状态（0为关闭，1为运行）
'prefix'=>'zzz_',//cookie,session，前缀，建议每个网站设不一样的

//静态缓存
'runmode'=>'0',//网站运行模式（0为动态，1为静态）
'htmldir'=>'',//静态生成路径（可为空，建议为a/）
'iscache'=>'0',//缓存模式（1开启）
'cachetime'=>'1',//单位小时，默认1小时
'siteext'=>'',//链接后缀（可以为空或.htm,.html,.php,.jsp）
 
//后台分页设置
'pagesize'=>'20',//默认分页数量
'sortsize'=>'300',//分类折叠数量

//数据库，支持mysql，sqlite，access，推荐使用mysql
'db'=>array(
'type'=>'sqlite',//数据库类型
'showsql'=>'0',
'tablepre'=>'zzz_',
//mysql
'host'=>'',//数据库地址
'port'=>'',//数据库端口
'name'=>'',//数据库名
'user'=>'',//数据库帐号
'password'=>'',//数据库密码
'charset'=>'utf8',
'engine'=>'InnoDB',
//access
'accesspath'=>'',
'accessname'=>'',
//sqlite
'sqlitepath'=>'',
'sqlitename'=>'',
),
//会员功能(0,1)
'usermark'=>'1',//会员功能开关
'passtry'=>'5',//密码错误重试次数
'ischeckmobile'=>'1',//是否验证手机
'ischeckemail'=>'0',//是否验证邮箱
'usercode'=>'1',//会员登陆注册是否需要验证码
'useronoff'=>'1',//是否需要审核，0为需要,1为不需要

//留言功能
'gbookmark'=>'1',
'gbookcode'=>'1',//留言验证码，建议开启
'gbookonoff'=>'1',//是否需要审核，0为需要,1为不需要
'gbookuser'=>'0',//是否要求会员
'gbookanonymousnum'=>'8',
'gbookusernum'=>'9',
'gbooktitle'=>'标题',
'gbooktitle_test'=>'*',
'gbooktitle_onoff'=>'1',
'gbookname'=>'姓名',
'gbookname_test'=>'*',
'gbookname_onoff'=>'1',
'gbooktel'=>'手机',
'gbooktel_test'=>'m',
'gbooktel_onoff'=>'1',
'gbookmail'=>'邮箱',
'gbookmail_test'=>'e',
'gbookmail_onoff'=>'1',
'gbookcontent'=>'内容',
'gbookcontent_test'=>'*',
'gbookcontent_onoff'=>'1',

//手机网站
'wapmark'=>'1',//手机网站开关
'wapautogo'=>'1',//手机自动跳转
'padautogo'=>'1',//平板自动跳转
'wappath'=>'wap/',

//上传文件目录
'uploadmark'=>'1',//上传设置开关(0为关闭，1为开启)
'uploadpath'=>'upload/',//上传文件根目录
'datefolder'=>'0',//是否创建日期文件夹(0为关闭，1为创建，图片较少建议关闭)
'covermark'=>'1',//同名是否覆盖（0为增加编号上传，1为覆盖,2为略过）

//图片上传限制
'imageext'=>'jpg,jpeg,gif,png',
'imageformat'=>'{yy}{mm}{dd}{hh}{ii}{ss}{rand:6}',//明明规则另外还有{pinyin}拼音,{filename},{yy}{mm}{dd}{hh}{ii}{ss}{rand:6}
'imagemaxsize'=>'2mb',//请注意空间上也会有限制上传大小
'compresswidth'=>'2000',//图片最大宽度
'compressheight'=>'2000',//图片最大高度
'compressquality'=>'80',//图片压缩质量
//附件上传限制
'fileext'=>'pdf,txt,doc,docx,xls,xlsx,zip,rar',
'fileformat'=>'{pinyin}',//附件命名规则
'filemaxsize'=>'10mb',//附件上传限制大小
//视频上传限制
'videoext'=>'mp4,flv,swf',//请注意空间90%以上不允许上传视频，或不支持视频格式
'videoformat'=>'{pinyin}',
'videomaxsize'=>'20mb',

//缩略图
'smallmark'=>'0',
'about_mode'=>'5','about_width'=>'300','about_height'=>'300','about_quality'=>'80',
'brand_mode'=>'5','brand_width'=>'400','brand_height'=>'400','brand_quality'=>'80',
'product_mode'=>'5','product_width'=>'300','product_height'=>'300','product_quality'=>'80',
'news_mode'=>'5','news_width'=>'300','news_height'=>'300','news_quality'=>'90',
'case_mode'=>'5','case_width'=>'300','case_height'=>'500','case_quality'=>'80',
'photo_mode'=>'5','photo_width'=>'500','photo_height'=>'300','photo_quality'=>'80',
'down_mode'=>'5','down_width'=>'300','down_height'=>'400','down_quality'=>'80',
'job_mode'=>'5','job_width'=>'350','job_height'=>'350','job_quality'=>'80',
'video_mode'=>'5','video_width'=>'400','video_height'=>'500','video_quality'=>'80',
'slide_mode'=>'5','slide_width'=>'400','slide_height'=>'500','slide_quality'=>'80',

//水印参数
'watermark'=>'0',//水印(0,1)
'watertype'=>'0',//水印类型(0为文字，1图片)
'watermarkfont'=>'zzzcms发生地方',//水印文字
'watermarkpic'=>'/images/logo.png',//水印图片
'markpicwidth'=>'100',//宽
'markpicheight'=>'30',//高
'markpicalpha'=>'1',//透明度
'watermarklocation'=>'1',//位置
//短信
'smsmark'=>'0',//短信开关
'smsid'=>'',//短信接口账号
'smspw'=>'',//短信接口密码
'regsendsms'=>'0',//注册发送验证码
'forgetsendsms'=>'0',//忘记密码发送验证码
'plugurl'=>'zzzcms.com', //授权域名，只填写主域名即可，不加www

//邮件设置
'mailmark'=>'0',
'smtp_server'=>'smtp.qiye.163.com',//邮件服务器
'smtp_mail'=>'kf@zzzcms.com',//邮件地址
'smtp_name'=>'zzzcms',//邮件地址
'smtp_ssl'=>'0',
'smtp_debug'=>'0',
'smtp_charset'=>'utf-8',
'smtp_port'=>'25',
'smtp_user'=>'kf@zzzcms.com',//邮件账号
'smtp_pass'=>'123456',//邮件密码
'receive_email'=>'kf@zzzcms.com,365661@qq.com',//接收邮件地址，支持多个邮箱逗号分隔分隔
//邮件提醒
'gbooksendmail'=>'1',//留言提醒
'evalsendmail'=>'1',//注入提醒
'regsendmail'=>'1',//注册提醒
'loginsendmail'=>'0',//登录提醒
'forgetsendmail'=>'0',//忘记密码提醒
'shopcatsendmail'=>'0',//加入购物车提醒
'shopordersendmail'=>'0',//加入订单提醒
'commentsendmail'=>'0',//评论提醒
'submissionsendmail'=>'0',//投稿提醒
'diyformsendmail'=>'0',//自定义表单提醒
);